[project]
name = "algo-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.11.0",
    "decorator>=5.2.1",
    "deepdiff>=8.6.1",
    "inflection>=0.5.1",
    "langchain-experimental>=0.4.0",
    "langchain[all]>=1.0.5",
    "matplotlib>=3.10.7",
    "networkx>=3.5",
    "numpy>=2.3.4",
    "openai>=2.7.2",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "yapf>=0.43.0",
]
